### ISSUE TITLE
Empyrean Campaign ideas: Act I

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#219]
**Spoiler Alert - This entire thread will contain Spoilers**

**Comment by igorko** [comment]
@dorkster It would be cool to see our cool engine features in empyrean, which were used in noname mod and poly, like minions, enemies that selfdestruct on contact, summoning powers, transforms, minions that summon minions, item sets... Well, a lot of cool engine features were used in above two games. @johndh, you can help to write story (quests) if you still interested, just contact @dorkster , currently he is the main person who writes the story

**Comment by dorkster** [comment]
@igorko I don't want to use features just for the sake of using them. As an example, having the player transform doesn't really fit with the theme of the Empyrean campaign's world. Polymorphable is already a showcase of transformations. anyway.

That said, here's what I *would* like to include from what you mentioned:

- Item sets. Each main dungeon has 2 mini-bosses and 1 boss. At a minimum, each will drop 1 piece of an item set (this is already a thing in the first dungeon)
- Minions/summoning. I'd like to have consumable scrolls for sale in later levels of the game that allow summoning (undead) creatures for a brief time. Since the player will be approaching the Underworld, implications of necromancy seem fitting.
- While not specifically selfdestruct-on-contact, I think we can make more use out of enemy power triggers that aren't "melee" or "ranged". e.g. The Goblin Chief casts his shield when joining combat.
