### ISSUE TITLE
Everything so small

### ISSUE THREAD

**Issue by Zaraka** [clintbellanger/flare-game#277]
Today I was testing my translation and try play a little bit, but after while I noticed everything feels so small, too small to play. I tried changing resolution, but it only make View-port smaller or bigger.  The only way which helps was changing to fullscreen mode in lower resolution, but text started to be blurry and l don't really like fullscreen (SDL fullscreen always turn off my second screen). It's very big request, but could you make some zooming function? Scale every tile in the screen except GUI, collisions could be problem. SDL_gfx have some zooming function...

**Comment by dorkster** [comment]
Closing this, because we have no plans on changing this in the near future.

1. Clint is on a break from game dev, so we won't see a full set of higher resolution art any time soon.
2. Real-time scaling is out of the question for the 1.0 engine. We're still supporting SDL 1.2 for systems where that is the only option. This means we can't use the fancy GPU accelerated bits of SDL 2 for scaling.

**Comment by igorko** [comment]
Just was reviewing issues, this request was implemented in master repo, we don't support SDL1.2 in master branch anymore, we use SDL2 and support scaling. Try it!

**Comment by nitramr** [comment]
Hi, I've created an updated HDCore for fantasycore and empyrean-campaign. At this moment I just scaled the images up to double size and changed all settings and animation txt files for the new image resolutions. So in fact for the gamer there is no better quality so far.

In next steps the graphic sprites have to be replaced step by step with a better quality. Icons are done. I used some of the images from Clint Bellangers old HDCore repository (https://github.com/clintbellanger/flare-hdcore)

You can find the updated HD core here:
https://github.com/nitramr/flare-game_fantasycoreHD
https://github.com/nitramr/flare-game_empyrean_campaignHD

**Comment by billywade** [comment]
I found a (hacky) solution to this: when running flare from the terminal with DPI scaling on, it'll tell you what your device DPI is. To change the zoom level, go to /mods/fantasycore/resolutions.txt and set virtual_dpi to a value lower than your actual DPI. 

It looks like it'll only scale to about half of your actual DPI and because the textures are intended for use at a higher resolution can appear blocky or fuzzy, but it's at least a start.
