### ISSUE TITLE
World interaction crash

### ISSUE THREAD

**Issue by 2mac** [clintbellanger/flare-game#458]
Clicked a barrel in the room with the mini-boss for the ice statue, and the game crashed. Wasn't running from terminal, so any stderr logging was lost unless there's a log file.

**Comment by dorkster** [comment]
@2mac Could you tell us which version of the game you are playing (e.g. v0.19, latest git master, etc)?

**Comment by 2mac** [comment]
Version 0.19, as distributed in Debian Sid.

**Comment by dorkster** [comment]
I was unable to reproduce this when testing on 0.19. However, it sounds related to [this bug (that has since been fixed)](https://github.com/clintbellanger/flare-engine/issues/1197) that occurred in the same room.

When you clicked on the barrel, it erased the event from the vector of map events, as intended. The problem was that Events weren't copied correctly internally in the events vector, so if any event had created a StatBlock, it would be freed twice and cause a crash. The Runed Chest in the aforementioned room created a StatBlock in such a manner, so that's why this bug has turned up here before.

So I'd say it's very likely this bug has already been resolved upstream.

**Comment by 2mac** [comment]
Sounds good. I await the next update.
