### ISSUE TITLE
Can see "inside" walls of cave tileset

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-game#476]
![cave_compare](https://cloud.githubusercontent.com/assets/913982/10412339/8bf41b40-6f50-11e5-88cb-807f452bcf45.png)

In the above image, the wall on the left is a direct render from Blender. The wall on the right is the same wall in the in-game/Tiled tileset. In both images, there is some amount of light hitting the inside part of the wall. This area should be pitch black to match the game's background (see the grassland and dungeon walls).

What I'm confused about is why the two images above are different. Was the image on the right made solely with Blender, or was there some post-processing afterwards? If it's the latter, I could create a "mask" file that can be merged with the rendered tileset walls.

**Comment by clintbellanger** [comment]
I think it may be something that changed in Blender, not in the way it's rendered. I'd found some way to render so that backfaces were black, and at some point it wasn't working for me anymore.

For new art I'm making, I'm using thick geometry instead.

**Comment by dorkster** [comment]
Okay, then I'll work on making the cave walls "thick" on the Blender side.

**Comment by dorkster** [comment]
[Finished](https://github.com/dorkster/flare-game/commit/a8b563e67b9d8f808d31a7a2b245aae2c5e25d5b#diff-1585ac610998de38ca3434b0196f0728)! And I even found a few corner tiles that were missing (ids 116-121).

However, mushrooms and spider webs appear to be darker. Any ideas as to why that would happen?

**Comment by igorko** [comment]
Can we have scripts for generating tilesets from blender sources without doing any manual work?

**Comment by clintbellanger** [comment]
Each tileset is so specialized, I doubt there's much automation that can be added.

**Comment by igorko** [comment]
Well, at least one script for one tileset, it would be very cool to be able to generate tileset with one click. That will allow e.g. change light for each model, save sources and regenerate tileset with one click, or change view type, and generate normal textures tileset etc. I have no idea how you guys update tilesets from blender without any automation.

**Comment by clintbellanger** [comment]
An idea of what that would involve.

You'd have one script that called each Blender file in succession, which would each auto-generate images. Then a complex script version of tilesetdef would combine all those images into the tile set.

Right now, most of the older Blender files have no automation. They often contain multiple tiles that have to be moved into camera view. rendered, file renamed, and moved back off camera, for each tile. Sometimes the lights and cameras are moved instead. Sometimes tiles are created with renders, or animations, or python scripts. Sometimes texture and light settings have to be changed between tiles in the same file, and I don't know how to do it automatically in Blender.

I think there are too many moving parts to make an automatic workflow, that wouldn't break as soon as you wanted to change something significant.

Because of the volume of work on these tiles, and the variation of strategies used, they basically have to be a forward process. Pick the lights and view and stick with it, because it's too much work to do twice or to fully automate. 

And, these old tiles are truly poor quality. They aren't meant to hold up in different light scenarios, or different views, or at larger zoom levels. Putting a ton of work into supporting these would be not well spent, in my opinion.

**Comment by igorko** [comment]
@clintbellanger Are you working on high quality tileset for Flare v2? If so. it would be nice to get some tilesets for testing/finishing dynamic lights support for flare-engine-next

**Comment by clintbellanger** [comment]
@igorko I'll be working on new tiles soon. Right now I'm making a few pieces of starter equipment and setting up a new core mod to test the hero animations. Part of that will be creating test floor and wall sizes for this new style, and those will become tile templates.

**Comment by clintbellanger** [comment]
These boots and trousers are items I'm working on over the last week http://i.imgur.com/tHmgxsV
Those will be starting items, or maybe items at the first vendor.

**Comment by dorkster** [comment]
The new cave tileset is now upstream. If you wish to continue discussing automation of tileset rendering, please open a new issue.
