### ISSUE TITLE
Could we have more clothing and scrolls? 

### ISSUE THREAD

**Issue by McSinyx** [clintbellanger/flare-game#492]
I've been playing Empyrean for a while, and it's absolutely the best RPG I've ever played (well, I had a kind of non-gaming childhood). Which slightly bothers me is that there are not many kinds of cloths. I mean, there are just the starter's normal cloths, the brute's armors, the scout's leather stuffs and the adept's thing (I don't know how to call this as my English is not so good). Could we have more appearance for the character? I'm playing adept and I think we may have color changing for cloths, e.g. silk ones in blue, velvet ones in white or sth like that. Also I think the rods and staffs' head look bit to high contrast (they look like few plain red/green pixels accidentally dropped into the screen, see picture below).

![2016-01-31-164955_640x480_scrot](https://cloud.githubusercontent.com/assets/13689192/12701371/b52bfd28-c83a-11e5-9cd7-72f9569bd78c.png)

I also really like the idea of scrolls. Could we have more of them, like antlion scrolls and wyvern scrolls?

Thanks for the great game. Sorry for my bad English.

**Comment by dorkster** [comment]
Glad to hear you're liking the game!

I agree that the Adept's robes need more variation. I was thinking of using the green and blue colors from the starting set of clothes, so that we can still mix-and-match armors without breaking style. Green would be used for the Silk robes, and blue would be used for the Velvet robes.

More scrolls are definitely planned. So far, I plan on having scrolls to:

- Summon an antlion
- Grant temporary haste
- Create a small damage shield

More ideas are always welcome.

**Comment by McSinyx** [comment]
Great! Thanks!

Also it's just me or the graphic gets blur when enlarged (though I think this is the engine's fault)?

**Comment by dorkster** [comment]
>Also it's just me or the graphic gets blur when enlarged (though I think this is the engine's fault)?

Our game assets are at a scale appropriate for 640x480. This is because of two reasons:

- Most of our 3D models are old and of a low quality. Rendering them at a higher resolution only uses more memory and doesn't give a significant improvement in visuals.
- Some of our effects are pieces of 2D art that lack source 3D models. So we are unable to re-render those at a higher resolution.

So yes, the engine scales everything up to fit in the window. That way, the same amount of the map is visible if you're playing on a tiny netbook or a 1080p tv. By default, we apply bilinear filtering when scaling up. If you want a more "pixelated" display with harder edges, disable the "Texture Filtering" option in the configuration menu.

**Comment by dorkster** [comment]
Finally got around to [adding some more scrolls](https://github.com/clintbellanger/flare-game/commit/5de4d2827abce0460ef527bf17905d7ee86011ee). So, here are our 8 available scrolls (one for each icon):

- Summon Zombie
- Teleport to Perdition Harbor
- Damage Shield (compare to the mage's Shield spell)
- Fireball (compare to mage's Fireball)
- Ice Bolt (compare to mage's Ice Bolt)
- Haste (compare to the ranger's Haste spell)
- Immunity (compare to the warrior's War Cry spell)
- Reflect (100% missile reflection + 25% damage reflection)
