### ISSUE TITLE
Warning (error message) printed when starting new game

### ISSUE THREAD

**Issue by hansjoachim** [clintbellanger/flare-game#506]
Steps to reproduce:
1. Start new game.
2. Pick a character and click Create.
3. Observe the output in the terminal.

Whenever I start a new game it prints `isDirectory: No such file or directory?`. Not sure why or how severe it is, but it doesn't look like expected behaviour. (I'm running Flare on Ubuntu in case this only shows up on some operating systems.)

Happens whether I attempt to play empyrean or the alpha demo.

**Comment by dorkster** [comment]
This is nothing severe. Our function for creating directories first checks if the directory exists. We print the error when that check fails.

For clarity, I've made it so that the file path in question gets printed out as part of the error message: https://github.com/clintbellanger/flare-engine/commit/28b983361e28989eea3b901532637d9892f61699

**Comment by hansjoachim** [comment]
>This is nothing severe. Our function for creating directories first checks if the directory exists. We print the error when that check fails.

Figured it might be something like this, though I hadn't gotten around to checking the source code.

Btw, I've played through the most recent maps in the Empyrean campaign, and I like the progression. :) (In my case, this was roughly from the Breach and beyond)
