### ISSUE TITLE
Do we still need minicore after adding dynamic scaling to engine

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-game#508]
Did anyone try to set resolution to 320×240 when playing alpha demo? Does it work?

**Comment by dorkster** [comment]
I brought this up in a [previous thread](https://github.com/clintbellanger/flare-engine/issues/1436#issuecomment-171446773) about the GCW-Zero with @zear:

>Could you try changing required_width and required_height in mods/fantasycore/engine/resolutions.txt to 320 and 240 respectively? You will also might need to change the resolution setting to 320x240 in ~/.config/flare/settings.txt for this to work, but it should scale everything down to 320x240 without needing the minicore mod.

Unfortunately, there was no response to that. If anyone with a GCW-Zero could test this, I would greatly appreciate it.

My main concerns about using run-time scaling over minicore are:

- Scaling isn't free. Devices that use minicore are already low-powered, so the run-time scaling might make the framerate dip too far down
- Memory. Using the normal size textures will use more RAM than the ones in minicore. I'm not sure how much memory is typically available to applications on the GCW-Zero.

**Comment by zear** [comment]
@dorkster 
I will try to test it as soon as I find some free time (I was very busy with other projects recently).

Retail GCW Zero units have 512M of RAM (development units - 256M). Memory available for applications on the retail units is ~498M.
Scaling on GCW Zero is actually free because of dedicated IPU hardware, however drawing in a larger resolution isn't.
Flare on GCW Zero already suffers from long loading times between sectors (measured in seconds). I worry that switching to a regular data set would only extend this.

**Comment by zear** [comment]
@dorkster 
@igorko 
I gave alpha_demo a try at 320x240 on GCW Zero and the results are as follows:
* The game suffers from noticable framerate drops. It went from fullspeed to at least half of that - way below a playable threshold for me.
* There is a noticable graphical blur that makes smaller objects unrecognisable.
* Menu elements and fonts are too tiny to be readable on a 320x240 screen. Although I think that could be adjusted by rendering those elements at a larger scale.

Overall, GCW Zero is still a viable reason for support of the minicore mod.

**Comment by dorkster** [comment]
Okay, those sound like good enough reasons to me to keep minicore. Thanks for taking the time to test it out.
