### ISSUE TITLE
16:10 Monitor resolution not auto detected or available

### ISSUE THREAD

**Issue by gnarlin** [clintbellanger/flare-game#511]
Hello.
I have a 16:10 Samsung monitor with a resolution of 1920x1200. The GUI doesn't offer this resolution.
I manually edited the config and that worked but it would be nice if my resolution was auto-detected and set on first startup or at least in the list of resolutions.

**Comment by dorkster** [comment]
Resolution detection for us is limited to what SDL itself reports.

However, since we moved to SDL 2, we ditched the resolution setting. We replaced that functionality with the ability to resize the game window. The game will then scale itself to fit in the window. So resolution settings are no longer an issue.
