### ISSUE TITLE
Balance of "agility"

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#517]
While playing flare-game, I found it a bit strange, how fast player's accuracy and evasion grows. I play with melee-paladin hero, so he is supposed (in my mind) to have powerful attacks and great armor/health, not that "offence"-assasin abilities. Anyway, at level ~10 he already have >100% accuracy (and I can't remember a moment, when I messed any attack) and >100% evasion, which, however, doesn't make him immune to physical attacks, but still lets enemies miss with about 60-70% chance.

I think, it's kinda OP, because I did not ever maximize my "offence" attribute, and it seems like noone have to up it ever (until to increase ranged damage). And, at least, that aspect have to be discussed.

**Comment by dorkster** [comment]
I agree that accuracy/avoidance have been unbalanced. I've made the following changes so far:

- Removed the hard-coded +25 given to accuracy in the engine. I'm not sure why that was there in the first place. Perhaps a relic from the early days of the engine?
- Drastically lowered the bonuses given to accuracy and avoidance from equipment.
- Lowered the accuracy and avoidance awarded per level to the player from 5 to 3.

So far, I'm happy with how this plays. Putting points into Offense and finding relevant equipment is more valuable now.

**Comment by DoKel** [comment]
That's nice :)
Btw, may I know, how that numbers over 100% work?) Kinda, accuracy of attacker somehow interacts with evasion of target and from that appears chance to miss?

**Comment by dorkster** [comment]
The formula is pretty simple:
```
chance to miss = 100 - (source accuracy - target avoidance)
(note, we then make sure this value fits between 0 and the max avoidance value. We don't set a max value for our game.)
```

So if the player has 125% accuracy and an enemy has 50% avoidance...
```
100 - (125 - 50) = 25% chance to miss
```

Having percentages >100% might seem weird to people new to the game, but I believe [Andor's Trail](https://play.google.com/store/apps/details?id=com.gpl.rpg.AndorsTrail&hl=en) does something similar with their accuracy and dodge stats.

**Comment by clintbellanger** [comment]
That +25% was to set up the default level one character a 75% chance of hitting a level one creature.

Chance of hitting is attacker accuracy minus defender avoidance. But I also wanted the numbers to line up so that an unskilled attacker has base 75% hit and an unskilled defender has a base 25% dodge, so the numbers are intuitive at level 1. The 75% accuracy assumes an opponent with default 25% dodge, thus still means a 75% chance to hit. That's where the 25% offset happens.

Why 75% accuracy? It feels fun to land most hits. 50% accuracy is not fun. Diablo starts with similar accuracy. 

75% attack vs 25% dodge means 75% hit chance. 
75% attack vs 50% dodge means 50% hit chance. 
100% attack vs 25% dodge means 100% hit chance. 
100% attack vs 50% dodge means 75% hit chance. 

If instead the enemy had default 0% dodge, they would never be missed, making accuracy useless. So I use 25% instead. 

And, if the player shows 75% accuracy at level 1, that should be reliable and mean hitting 3/4 attacks. Even though starting enemies have 25% avoidance, the player doesn't see that, and should not start off with an actual 50% calculated accuracy. 

There may be a better way to arrange that, but I find it gives the displayed accuracy meaning. 

And side thought, I would advocate removing accuracy as a player stat entirely. It's preferred in action games to let every collision be a hit, instead of random misses which make more sense in turn based games. I'd give everything base 100% accuracy and only give players ways to upgrade avoidance. I'd then make crit the "agility" bonus instead of accuracy. OR, use a system where overhits (player had >100% chance to hit and rolled above 100) are converted to crits.

**Comment by dorkster** [comment]
@clintbellanger That's what I thought, except this doesn't make sense to me:

>If instead the enemy had default 0% dodge, they would never be missed, making accuracy useless. So I use 25% instead.

Given a 75% source accuracy, this should still result in a 25% miss chance. Inversely, the chance to hit is 75%. The math would be: `100 - (75 - 0) = 25`. It can absolutely be expressed in the game data, so we don't need the magic number in the engine.

----

As for removing accuracy all together, I see where you're coming from. However, I disagree. The assumption is that we'd be replacing the dice roll with player movement skill. Here's why I don't think we can make that trade:

- **The player movement**: Many action games that require player movement skill offer various types of movement. Some have "combat rolls" as a way to dodge incoming attacks quickly. Some have a third dimension, allowing for jumping and other vertical movement. Flare has neither.
- **The enemy movement**: The movement patterns of enemies are pretty predictable. They will take the shortest path straight for the player. Then once engaged in combat, they rarely move unless the player also moves. The "fleeing" state for enemies adds some unpredictability, but very few enemies use it.
- **Attack speeds**: If we want to expect players to be able to dodge enemy attacks, the attacks would need to be telegraphed for the player to discern in a reasonable time frame. Right now, I think our attack animations are two fast to be reacted upon.
- **Entities can't move while attacking/being hit**: This is a weaker point, but its still something that slows the pace of combat.

----

Anyway, I've tried to design the new combat numbers so that hits land >=75% of the time through most of the game. Players might have some trouble if they completely neglect those stats in the late game, but that's by design.

**Comment by dorkster** [comment]
Idea: What if turned "misses" into reduced damage? Kind of like Torchlight does. That way, hits are always landing, but there's an incentive to land "good" hits.

**Comment by clintbellanger** [comment]
What I meant by that confusing part - setting an enemy's dodge to 0% makes the formula 100 - (75 - 0) work fine. But it's weird to set an enemy with "zero" avoidance and then seeing the player still miss the enemy 25% of the time. I wanted 75/25 to be the numbers used and shown at level 1, to have clear expectation that those match the starting hit and miss ratios. For both modders and players. But the meaning of that gets confusing after level 1.

That's fine though, as long as the modders know the formulas. This new one is easier to explain than what I was doing before with the weird 25% 'normalization'.

**Comment by dorkster** [comment]
Thanks, I get it now.

I did some more play testing and found myself missing more than I wanted to. So I think I'm going to try doing reduced damage on misses as I mentioned above. It makes sense physically, too. Think grazing an enemy's leg vs a direct blow to the head. Head would probably hurt more.

**Comment by clintbellanger** [comment]
I do want to try experimenting with "100% accuracy" player attacks in the Wandercall combat. That will involve a lot of the challenges you mention above, like getting enemies with slow attacks (see: ogre) and a variety of movement patterns. 

Warrior powers of the style Charge / Bullrush can sort of double as a dodge in Flare, right? I think between block and charge, melee characters have some defensive options.

**Comment by dorkster** [comment]
I finished implementing the "damage reduction for misses" feature, and I'm really happy with the results. I've set our game to use a 50-75% reduction in damage whenever a miss occurs, which seems to be working well. I think its even improved the game's balance:

- Before, players with very low accuracy (warriors & mages) might end up never doing damage to an enemy. Now, the player is guaranteed to do a reasonable amount of damage. So in reality, the accuracy/avoidance stats are less important, but still serve as a "bonus" to damage output.
- Since all enemy attacks now hit the player, the poise stat is more valuable for melee characters.

**Comment by DoKel** [comment]
Damage reduction for misses is really nice feature, i like it! :3
But what about converting "overhits" to crits, for having no just miss-reduction but also highaccuracy-amplification?

**Comment by dorkster** [comment]
I like the idea of overhits, so I'll definitely try experimenting with it. Although it's not a priority right now.

**Comment by dorkster** [comment]
Overhits are [in the engine](https://github.com/clintbellanger/flare-engine/commit/8f46e23f10fdeeaadb3c75e9e20c6723f56316f6) now. I think a 1.25-1.5x multiplier is suitable for our game, so I've [set it accordingly](https://github.com/clintbellanger/flare-game/commit/bf41478209cf49369da8d93183880c7b9e14fd51).

**Comment by clintbellanger** [comment]
This is neat. It addresses a worry I had with the stat for a while, that accuracy's effectiveness was ambiguous after getting 100%. Now there's a good reason to keep spending points, that continues to be good like the other stats.
