### ISSUE TITLE
Items require Mental points AND Mental points

### ISSUE THREAD

**Issue by sang-froid** [clintbellanger/flare-game#537]
- Context : I play Empyrean Campaign. I find Warlord cloth shirt. I look at its characteristics.
- Expectation : It should require defense points and physical points (for instance).
- Observation : It requires mental points and mental points.

By the way, this is my first bug report ever. I am a teenager. My father helps me with the English translation. I love Flare. Thank you Clint !

**Comment by clintbellanger** [comment]
You're welcome, from the whole team :) Thanks for this report

**Comment by dorkster** [comment]
Thanks for playing, and thanks for the bug report.

First, make sure your mod configuration is correct as explained [here](https://github.com/clintbellanger/flare-game/issues/538#issuecomment-316373267). If the shirt still has the wrong stat requirements, make sure you have the latest version of the `empyrean_campaign` mod, since the requirements [look to be okay](https://github.com/clintbellanger/flare-game/blob/master/mods/empyrean_campaign/items/categories/level_4.txt#L11).

**Comment by sang-froid** [comment]
Sorry, but in fact I noticed that it was a translation error in French. I will send a Pull request to improve the translation.
Thank you for your help.
