### ISSUE TITLE
Following Readme - start Flare-game failed

### ISSUE THREAD

**Issue by scottfurry** [clintbellanger/flare-game#555]
README file for flare-game details how to build and run on Linux.
Followed instructions to clone repositories - no errors
All dependencies met and build of game engine successful
Followed "option 2" for running game w/o installing.
Received error:
```
[flare-game]$ ./flare --game=flare-game
ERROR: '--game=flare-game' is not a valid command line option. Try '--help' for a list of valid options.
ERROR: ModManager: Error during loadModList() -- couldn't open mods.txt, to be located at:
ERROR: /home/user/.config/flare/mods.txt
./mods/mods.txt
INFO: No joysticks were found.
ERROR: Settings: save_prefix not found in engine/misc.txt, setting to 'default'. This may cause save file conflicts between games that have no save_prefix.
ERROR: FileParser: engine/loot.txt: Could not open text file: No such file or directory!
INFO: Using Render Device: SDLSoftwareRenderDevice (software, SDL 2)
ERROR: Settings: save_prefix not found in engine/misc.txt, setting to 'default'. This may cause save file conflicts between games that have no save_prefix.
ERROR: FileParser: engine/loot.txt: Could not open text file: No such file or directory!
```
I would get the Flare main window but "Play Game" button was disabled.

From flare-engine README page, game flag is not listed. Docs out of date?

**Comment by scottfurry** [comment]
NVM...
Answer was in non-Linux build instructions above.
Mods for fantasycore and alpha_demo needed to be enabled.

**Comment by dorkster** [comment]
You're right that the `--game` flag is out of date. I've fixed this. The instructions for option 2 look correct, and seem to be the same as [this section](https://github.com/clintbellanger/flare-engine/blob/master/INSTALL.engine.md#clone-build-and-play) of the engine documentation.

Alternatively, you can symlink the mods in the user's data directory (`~/.local/share/flare/mods/`). This is personally what I do so that the `flare` executable can reside anywhere without having to install flare-game system-wide.
