### ISSUE TITLE
It would be better to reduce Requires Defense of the leather series armor from 2 to 1.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#586]
I think that the leather series's Requires Defense should be reduced from 2 to 1.

In the real world, even children can wear leather jackets. A lady may carry a leather bag. So, I think that it doesn't need  strong power to equip the leather armor.

In addition, even if the player solved the first quest of Martigan and got the reward gold, then player cannot buy any armor for Brute and Scout at Lv1.

In most, RPG-games in Japan  ,it is often that even magicians and monks can equip leather armor.

Shopping is also one of the enjoyment of the fantasy-RPG, and it will also be a demonstration for the explanation of the shopping system of thia game.

If we keep the Requires Defence of wood buckler as it is (Requires Defence: 2), we can explain that it is necessary to raise the Defense to equip armor.

**Comment by clintbellanger** [comment]
True it's not realistic. I originally did this for game balance purposes, but that was long ago. Most other numbers have been changed since then, so there's no real balance reason to keep it this way.

(that was the required defense for leather at the very beginning of this project. 2009, when it was going to be turn-based and in Java)
