### ISSUE TITLE
Required stats is a little high, in empyrean_campaign.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#653]
About from around Nazia highlands, the hero often cannot equip the weapon and armors which the hero got , due to less of stats. 
For example hero's stats... 
Physical: 5
Mental: 5
Offence: 19
Defense: 19

Level 9

Although it is level 9,
and also despite being a point distribution considering on Offense and Defense considerably, even that the hero can not be equipped with Sniper Shortbow. (Sniper Shortbow require Offense 20)
Also, a Recon Chain Coif which is sold by abasi in Nazia Hilands cannot be equipped too. (Chain Coif require Defense 20)

We should lower the Required stats. For example, we should lower it by about 5. For example, we should change the Required stats of Sniper Shortbow to Offense 15.

**Comment by sujiniku** [comment]
In my memory, perhaps, the hero reached the Nazia plateau with level 7. 
At the time of arrival in Nazia, offense and defense were even lower than 19, perhaps,  about was 16 each.

**Comment by dorkster** [comment]
The current requirements for items are designed around the player splitting stat allocation between one damage stat and Defense. I don't like this because it doesn't leave much flexibility for builds. For each of the 4 stats, I've been using the following formula for requirements:

```
value = initial_value + (value_per_level * (item_level - base_level_for_item))
```

For the Sniper Shortbow, this ends up being:

```
offense = 2 + (3 * (8 - 2)) = 20
```

The **value_per_level** is what we want to tweak here. For items that have two stat requirements, we use a value of 1 for the minor value, and 3 for the major value. I think we can reduce the value_per_level of the major value to 2. Doing this will reduce the Sniper Shortbow requirement to 14, which would still be viable for your example of a slightly under-leveled character. That still seems fair to me while allowing for some player experimentation.

**Comment by sujiniku** [comment]
I agree your idea.
