### ISSUE TITLE
About flaregame/tiled folder,

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#658]
In flaregame/tiled folder, We should create a new folder called "alpha_demo" .
"frontier", "averguard" and "living_bones" should be in the "alpha_demo" folder.

**Comment by dorkster** [comment]
I agree.

**Comment by dorkster** [comment]
Note: I didn't keep the same directory structure inside the new alpha_demo directory. This is because these maps contain relative paths to the tileset images. Keeping the directory structure 1 level deep means we don't have to change these.

And it's not like alpha_demo has a lot of maps to begin with. empyrean_campaign has more, yet has a flat structure.
