### ISSUE TITLE
Need Info About Goblin's Ruby and Loren(Undead Trader)

### ISSUE THREAD

**Issue by dess55tr** [clintbellanger/flare-game#703]
Hello everyone,
Where can i use tis ruby to complete the quest?And in Mog Caverns; Loren is not talking to me, just '...'
I need help about these issues.
Thanks in advance

**Comment by dorkster** [comment]
Ort wants you to give the ruby to his brother, who is also a goblin. It is likely that you already met his brother, who is in fact the only other goblin you can interact with in the game.

<details/>
  <summary>spoiler</summary>
It's Bakat in Lake Kuuma
</details>

----

As for Loren, her dialog is intentional. Zombies don't have much to say. However, she should offer to trade with you after the initial dialog.

**Comment by dess55tr** [comment]
Thanks for infos.

But Loren is not offering me for trade

**Comment by dorkster** [comment]
That sounds like a bug to me. Can you post your [avatar.txt save file](https://github.com/clintbellanger/flare-engine#save-files)?

**Comment by dess55tr** [comment]
I don't know how to do it.But 5 worn notes in my inventory and i can't throw or sell them either

**Comment by dorkster** [comment]
What operating system are you using? If it's Windows, open the file explorer and paste in this `%APPDATA%\flare\userdata\saves\empyrean\`. You'll see several folders named with numbers. Open the one that corresponds with the "#" displayed on your saved game when you go to "Play Game" in Flare. Then open the avatar.txt in that folder and copy/paste the contents here.

**Comment by dorkster** [comment]
Oh, where did you get the mobile version? We haven't released it ourselves on any of the app stores, so you're likely playing a fork released by someone else. That would explain the bugs.

**Comment by dess55tr** [comment]
Then something is wrong here:) Please search 'Flare Bring Diablo 2 Back' on Google Play Store

**Comment by dorkster** [comment]
Yep, that is not us, but I'm aware of their existence. They forked our engine and made a vast amount of changes (I'm honestly quite impressed by some of them). However, they appear to be lagging behind our current state, hence the bugs.

Unfortunately, nothing we can do about it until they get their fork back up to date.

**Comment by dess55tr** [comment]
It is not ethical for someone to upload your game to a game store.Look at the bright side, you have noticed this in my case

Thanks for your interest.

**Comment by dorkster** [comment]
It's a strange situation. They give credit (I'm guessing that's how you ended up here), but haven't released the source code for their changes *and* have included ads in between map loads. It just feels wrong to me. It would also be nice if they changed the title to "FlareX", like it is in the description, to help differentiate it from our project.

**Comment by tvleavitt** [comment]
The mobile version they put out is how I found out about Flare. Since it was open source, I figured there must be a desktop version, and there was one. Thought it was strange that they had ads, and that their project was called FlareX and not Flare... had no idea that they'd forked your code; that explains it. And, wait... they haven't released the source code?!? Isn't that a GPL violation?!?

**Comment by vgaming** [comment]
I didn't know it's not "official" flare either. @tvleavitt has a good point, they should release their sources. I think it would make sense to write them and request releasing sources. If they refuse / not answer, write to google play. License is something that should be obeyed in either way.
