### ISSUE TITLE
Readme.md refers to old content

### ISSUE THREAD

**Issue by tvleavitt** [clintbellanger/flare-game#712]
Under "Building and Running (non-Linux)"

> Flare Game is installed as a set of mods for Flare Engine. Place the contents of the "mods" folder inside Flare Engine's mods folder.
> 
>     On Windows, the mods folder will be in the same directory as the flare executable.
>     On OSX, this will be inside the Flare.app folder, in Resources/mods

For OS X, this is not correct, if you're building from source, you wind up with "flare-game" and "flare-engine", and symlink to the flare-engine/flare binary from flare-game, and run ./flare from there. The only way you get a Flare.app folder, is if you install the "binary" from a DMG, and I don't think it is protocol to be messing around inside an application package.

> Then enable these mods in Flare's Configuration screen.
> 
> fantasycore
> alpha_demo
> 

Obviously, this refers to alpha content, not "empyrean-campaign". Also, I was told to add the "centered_statbars" mod to the OS X build as well.

**Comment by dorkster** [comment]
We should remove those messages, as `./mods/` is used on all platforms when using the build from source instructions. I'll fix the alpha_demo thing, too.

`centered_statbars` isn't required, but I included it in the release because some community members liked it. It's also a nice small example mod to demonstrate the modding system.
