### ISSUE TITLE
Create an Android version

### ISSUE THREAD

**Issue by KOLANICH** [clintbellanger/flare-game#714]

**Comment by dorkster** [comment]
The Android version we have is not quite user friendly in that it requires manually installing the game data. So we haven't promoted it much because of that.

I will still try to get an APK up for people that want to try it.

**Comment by dorkster** [comment]
Since getting the Android version set up is non-trivial, I've created a [wiki page](https://github.com/clintbellanger/flare-engine/wiki/Android-Port) that links to the APK, as well as providing instructions to install the game data. I've added a link to that page under the "Other distributions & platforms" section of our [Downloads](http://flarerpg.org/index.php/download/) page.
