### ISSUE TITLE
Some shortcuts require to be opened every time you visit a location

### ISSUE THREAD

**Issue by Arcanister** [clintbellanger/flare-game#727]
In most locations there is a shortcut, which is usually opened by a lever on the opposite side of the door. 

However in some locations the door stays open when you reenter the location, while in others you have to go through entire location again to open it from the other side. As far as I could see usually doors which require keys stay open while doors which use levers do not.

Maybe it makes sense to make some or all location shortcuts persistent? Or make the door triggered by a lever openable once the lever lowered, so door can stand as protection against monsters on other side.

**Comment by dorkster** [comment]
In many of the maps where shortcuts don't persist, it is done because the shortcut is close to the miniboss/treasure room. We don't want the player to be able to easily run through the shortcut, get the treasure, and then leave/enter the map to do it again.

For the shortcuts that *do* persist, it is because they are part of the main story path. The player can move more freely along this path once they've unlocked parts of the sequence.
