### ISSUE TITLE
Do not remove finished quests from log

### ISSUE THREAD

**Issue by un404known** [clintbellanger/flare-game#747]
It would be nice to keep a quest title to keep track of what you already did.

E.g. I am replaying the game with a different character and would love to compare what I missed / whether I missed something on one of both turns.

**Comment by McSinyx** [comment]
Also I think it's weird to have same notification about the main quest every time the game is loaded.

**Comment by dorkster** [comment]
I've added a property to quests so that we can set which status should be set to consider it "complete". With this information, we can now display a list of the completed quests. Also, the quest notification should remember its "read" state now, so it will only show if there's a quest update.

- https://github.com/clintbellanger/flare-engine/commit/95d005255e2aaadbfb834945098f89f68f46381e
- https://github.com/clintbellanger/flare-engine/commit/86684ec769d21fbe2243f0eef38f93c4588f5573
