### ISSUE TITLE
Empyrean Campaign: More item icon variety

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#759]
In Empyrean Campaign, there are a ton of items which share icons. These items can sometimes differ dramatically in their attributes.
This is not good, I find it sometimes hard to organize the items because icons are re-used so often.

Items often come in various “tiers”, i.e. quality levels. I believe a good start would be to split the item icons into tiers and make slight variations of the icons.

**Comment by dorkster** [comment]
One thing I experimented with in the past was drawing on the icons in engine using some of the item quality colors (green, blue, purple, etc). I ultimately couldn't decide between drawing a filled triangle in the top-left corner and drawing a simple rectangle border, so I just scrapped the idea. Might be worth revisiting with some alternate designs.

**Comment by Wuzzy2** [comment]
Hmm, trying to do this entirely in the engine might be tricky, and probably won't work with all sorts of different art styles, thus defeating the point of an engine somewhat.

I think a few manually-drawn variations of the icons can't hurt. Even just a few variations will be enough to reduce the number of duplicates drastically.

If you think about overlays, I would still “hardcode” that into the image instead of trying to do it in the engine.

One thing you *could* do in the engine would be playing with background color, and give mods full control over the background color for each item.

**Comment by dorkster** [comment]
I think mod-able overlays are the answer here. That way, they can be styled to the artwork, but still keep the amount of duplicate work to a minimum if showing item quality is all that's desired.

**Comment by Wuzzy2** [comment]
Yeah, that sounds sensible, too.

**Comment by brigazvi** [comment]
somthing like this?
![swords](https://user-images.githubusercontent.com/37640970/42084015-298c1788-7b95-11e8-83d7-9d9d2fe00eb6.png)

**Comment by dorkster** [comment]
@brigazvi I was thinking more along the lines of something like this:

![icon_test](https://user-images.githubusercontent.com/913982/42107348-01583ee4-7ba5-11e8-9751-058d66ce7e5c.png)

The colors here could be separate overlays that the engine could apply based on item quality. This has some advantages:

- Reduces the workload of creating multiple versions of each icon
- Keeps the base icon spritesheet size down
- Can be easily applied to new icons as we add them
- Has a consistent design language. At a glance, it will be easy to see the quality of any item without having to look at its tooltip

**Comment by nitramr** [comment]
I think to have a wider range of items it can be solved like this.

#### 1. Items can have different quality levels:
- old - useless, rusty, broken, damaged
- normal - used
- new - unused, sharp

That states can be represent with 3 different styles of icons only. Item images for sprite animations can be one and the same for all three states, because such details are to small to see a difference in game. (except in extrem HD resolution) :D

It is also an idea for a later crafting system that items can get broken and you can repair it.

#### 2. Items can have some color tints for attributes, like rare, unique, magical (ice, fire, poison, bolt), etc.
- simple colored overlay for icons (like in Dorksters proposal)
- simple color tint by engine for animation sprites

One example which I found comes from Diablo 2. Take a look to the green helmet. The sprites comes from the original uncolored helmet but just have a color tint on top to looks different. 
http://i1.ytimg.com/vi/b2ylCG01mwU/maxresdefault.jpg

**Comment by dorkster** [comment]
We now have icon overlays:

- https://github.com/clintbellanger/flare-engine/commit/a40d8a9d2a364ecdd7f1fb409d20764f531f7ae0
- https://github.com/clintbellanger/flare-game/commit/9a8ff1b1daf8c1f7db0b3b32d1ad51def068724b

Screenshot:

![screenshot_2018-07-24_18-40-56](https://user-images.githubusercontent.com/913982/43171054-5a54c3c0-8f76-11e8-834b-1d355890e578.png)
